#!/usr/bin/env python3
"""Render two presentation-friendly figures from existing CSVs.

This is a thin standalone script that bypasses the generic plot helpers
in ``src/visualization`` and produces two figures that are tuned for the
final-presentation slides:

* ``slide7_scaling.png`` -- runtime vs. n_foods on a log-log axis with
  large solid markers, a legend pinned outside the plot, and an opaque
  background. The previous version generated by
  ``src.visualization.results_graphics.build_runtime_scaling_figure`` was
  rendering as a near-empty plot in some viewers; this version pins
  every styling property explicitly so it is robust across exporters.
* ``slide8_preferred_day_hits.png`` -- bar chart of the ``preferred_day_hits``
  metric per solver. This is the empirical result that actually
  distinguishes joint CP-SAT from the two-stage decomposition (joint
  hits 3.82 of the user's preferred days on average vs. 3.27 for
  two-stage), making it a much better slide-8 figure than the
  "objective breakdown" which was identical across all four solvers.

Usage::

    python scripts/make_presentation_figures.py
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import matplotlib
matplotlib.use("Agg")               # headless-safe backend
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.config.settings import FIGURES_DIR, TABLES_DIR


SOLVER_COLORS = {
    "nutrition_only": "#2ca02c",
    "two_stage": "#d62728",
    "joint_cpsat": "#1f77b4",
    "joint_warmstart": "#ff7f0e",
}
SOLVER_MARKERS = {
    "nutrition_only": "o",
    "two_stage": "s",
    "joint_cpsat": "D",
    "joint_warmstart": "^",
}
SOLVER_ORDER = ["nutrition_only", "two_stage", "joint_cpsat", "joint_warmstart"]


def render_scaling(csv_path: Path, out_path: Path) -> Path:
    """Slide 7: runtime scaling on a log-log axis."""
    df = pd.read_csv(csv_path)
    df = df[df["runtime_s"] > 0].copy()

    fig, ax = plt.subplots(figsize=(11, 6), facecolor="white")
    ax.set_facecolor("white")

    for solver in SOLVER_ORDER:
        sub = df[df["solver"] == solver].sort_values("n_foods")
        if sub.empty:
            continue
        # Big solid markers + a connecting line so the trend is obvious
        # even on a 1080p projector at the back of a lecture hall.
        ax.plot(
            sub["n_foods"], sub["runtime_s"],
            marker=SOLVER_MARKERS[solver],
            markersize=12,
            color=SOLVER_COLORS[solver],
            linewidth=2.0,
            label=solver,
            zorder=3,
        )

    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("n_foods (catalog size, log scale)", fontsize=14)
    ax.set_ylabel("runtime seconds (log scale)", fontsize=14)
    ax.set_title("Solver runtime vs. catalog size", fontsize=16, pad=12)
    ax.tick_params(labelsize=12)
    ax.grid(True, which="both", linestyle=":", alpha=0.45, zorder=1)

    # Legend OUTSIDE the plot box so it cannot occlude data points.
    ax.legend(
        title="solver", loc="center left",
        bbox_to_anchor=(1.02, 0.5),
        fontsize=12, title_fontsize=12, frameon=True,
    )

    fig.tight_layout()
    fig.savefig(out_path, dpi=150, facecolor="white", bbox_inches="tight")
    plt.close(fig)
    return out_path


def render_preferred_days(csv_path: Path, out_path: Path) -> Path:
    """Slide 8: average preferred-day workout hits per solver."""
    df = pd.read_csv(csv_path)
    feas = df[df["feasible"]]
    means = feas.groupby("solver")["preferred_day_hits"].mean()
    means = means.reindex(SOLVER_ORDER).fillna(0.0)

    fig, ax = plt.subplots(figsize=(9, 5.5), facecolor="white")
    ax.set_facecolor("white")

    bar_positions = np.arange(len(means))
    bar_colors = [SOLVER_COLORS[s] for s in means.index]
    bars = ax.bar(
        bar_positions, means.values,
        color=bar_colors, edgecolor="black", linewidth=1.2,
        zorder=3,
    )
    for bar, value in zip(bars, means.values):
        ax.text(
            bar.get_x() + bar.get_width() / 2, value + 0.06,
            f"{value:.2f}",
            ha="center", va="bottom",
            fontsize=14, fontweight="bold",
        )

    ax.set_xticks(bar_positions)
    ax.set_xticklabels(means.index, fontsize=12)
    ax.set_ylabel("Avg. preferred-day workout hits / week", fontsize=13)
    ax.set_ylim(0, max(means.values) * 1.25 + 0.5)
    ax.set_title(
        "Where joint optimization actually pays off", fontsize=16, pad=12,
    )
    ax.grid(axis="y", linestyle=":", alpha=0.45, zorder=1)

    # Annotate the headline gap so the audience reads the story instantly.
    ax.annotate(
        "+0.55 vs two_stage",
        xy=(2, means.loc["joint_cpsat"]),
        xytext=(2.5, means.loc["joint_cpsat"] + 0.7),
        fontsize=12, color="#444",
        arrowprops=dict(arrowstyle="->", color="#444"),
    )

    fig.tight_layout()
    fig.savefig(out_path, dpi=150, facecolor="white", bbox_inches="tight")
    plt.close(fig)
    return out_path


def main() -> int:
    out_dir = FIGURES_DIR
    out_dir.mkdir(parents=True, exist_ok=True)

    scaling_csv = TABLES_DIR / "scaling_final_long.csv"
    final_csv = TABLES_DIR / "final_long.csv"
    if not scaling_csv.exists():
        raise SystemExit(f"missing {scaling_csv} -- run scripts/run_scaling_study.py first")
    if not final_csv.exists():
        raise SystemExit(f"missing {final_csv} -- run the experiments command first")

    scaling_path = render_scaling(scaling_csv, out_dir / "slide7_scaling.png")
    pref_path = render_preferred_days(final_csv, out_dir / "slide8_preferred_day_hits.png")
    print(f"Wrote {scaling_path}")
    print(f"Wrote {pref_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
